### ISSUE TITLE
Animation glitch in 6.6.0

### ISSUE THREAD

**Issue by short-dsb** [airbnb/lottie-react-native#1170]
### Description

There is an animation glitch in our Lottie file with 6.6.0 that was not present in 6.5.1. This issue occurs on both iOS and Android. We need to upgrade soon due to Apple’s [Privacy manifest for SDKs](https://developer.apple.com/videos/play/wwdc2023/10060/) requirement, so any help would be appreciated!

### Steps to Reproduce

1. Load and play the animation

**Expected behavior:** [What you expected to happen]

Animation plays without glitches.

**Actual behavior:** [What actually happened]

There is an animation glitch on the “X” in “SHORTBOXED” where only the bottom half of the character is rendered during the animation, then the top half pops in on the last frame. This issue is not present in 6.5.1.

### Minimal reproduction

[SplashScreen.json](https://github.com/lottie-react-native/lottie-react-native/files/14088634/SplashScreen.json)

### React Native Environment

```
❯ npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 13.6.3
  CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  Memory: 73.53 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.0/bin/npm
  Watchman:
    version: 2023.10.02.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/dsb/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20.1
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/dsb/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.10
    wanted: 0.72.10
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Lottie Version

Version: 6.6.0

**Comment by matinzd** [comment]
Hi
Have you tried your animation with lottie app on App Store and Google Play?

**Comment by TheRogue76** [comment]
> Thanks for checking it out!
> 
> Looks like `"SOFTWARE"` works but `"HARDWARE"` does not. What are the implications of using `"SOFTWARE"`? Performance?

Lottie V6 introduced a new way to render animations, moving most of the work from the CPU to the GPU so that the Main thread can have a much lower utilisation (and lead to better performance).

By default, It has an automatic variant that picks based on environment what thread to run it on ("AUTOMATIC") and that is the new default. "SOFTWARE" is the old behaviour from V5 that handles all the compute on the CPU side, And "HARDWARE" is explicitly using the newer mode with GPU Utilization. They are pretty compatible in most cases, but from time to time we get edge cases where one is using a feature that is not compatible with the other for the full list, [see here](https://airbnb.io/lottie/#/supported-features))

**Comment by TheRogue76** [comment]
I have a PR for adding explanations to the migration guide: https://github.com/lottie-react-native/lottie-react-native/pull/1172. Hopefully that will help others as well

**Comment by TheRogue76** [comment]
> Thanks for the info. 🙂
> 
> > They are pretty compatible in most cases, but from time to time we get edge cases where one is using a feature that is not compatible with the other
> 
> Will there eventually be full parity? It seems like `"HARDWARE"` is the preferred rendering method for performance.

I wouldn't know. That is up to the Native Platforms to implement on their side, but I assume any that they haven't added support for has a good reason. Lottie React Native is trying to be as minimal of a wrapper as possible so people don't end up suffering weird issues that a Native iOS / Android dev would not face and we want it to match their performance (Hence why we are going all in on New Architecture and Bridgeless).

**Comment by TheRogue76** [comment]
Perhaps my previous comment gave the wrong impression, the new architecture stuff is not a requirement for our library, simply something that we believe will unblock certain performance optimization pathways (we do have other ones available already, like using dotLottie files and loading assets on the Native side for people wanting to squeeze out as much performance as possible). We do not expect the consumers of the library to have new arch enabled, we are simply adding support for it so that the ones who do will be able to get benefits for it down the line.

As for continuing CPU rendering support, I don't see the Native platforms getting rid of it anytime soon, it's not blocking any feature development as far as I know (the scope of what Lottie is trying to solve is pretty well defined and well understood at this point), and so long as they support, we will support it too.

For your last question, I don't have a super great recommendation, If it's a JSON file, i just check to see if any of the unsupported effects are mentioned in it and check it with Logcat on Android to see if it invoked an unsupported feature. Something like this:
<img width="1586" alt="Screenshot 2024-01-20 at 12 03 25" src="https://github.com/lottie-react-native/lottie-react-native/assets/40071952/baeaa6c4-912f-433e-a098-7d7315705f2f">
