### ISSUE TITLE
Unable to find file (Android)

### ISSUE THREAD

**Issue by leesolway** [airbnb/lottie-react-native#194]
I have an issue with android. 

**Error :-**
Error while updating property 'sourceName' of a view managed by: LottieAnimationView

null

Unable to find file loading.js

**Animation file location :-**
app/src/main/assets/loading.json

**Component :-**
```
class Loading extends Component {

  componentDidMount() {
    this.animation.play()
  }

  render() {
    return (
      <View style={StyleSheet.loading.page}>
        <View style={StyleSheet.loading.animationWrapper}>
          <Animation
            ref={animation => { this.animation = animation }}
            style={StyleSheet.loading.animation}
            loop
            source="loading.json"
          />
        </View>
        <Text style={StyleSheet.loading.text}>LOADING</Text>
      </View>
    )
  }
}
```

**Versions :-**
"lottie-react-native": "2.2.0"
"react-native": "0.47.2"

**Comment by gpeal** [comment]
@leesolway I just tried this in the sample app that's in this repo and it worked so there may be something incorrect about your setup.

**Comment by JofBigHealth** [comment]
For anyone who's finding this via web search, these bugs are almost certainly because you need to supply the actual javascript object. A common way of doing this is with `require` like this

```
<Lottie source={require("./animation.json")} />
```

If you fetch the data from a remote url you'll need to `JSON.parse` and give that resulting object as the `source` prop.

From the documentation

source | Mandatory - The source of animation. This must be a JS object of an animation, obtained (for example) with something like require('../path/to/animation.json'). This is needed in order to fix thing
-- | --
