### ISSUE TITLE
LottieAnimationView.play was called with 3 arguments but expects 1 arguments

### ISSUE THREAD

**Issue by kytwb** [airbnb/lottie-react-native#235]
After upgrading to `lottie-react-native@2.3.0`:
```
LottieAnimationView.play was called with 3 arguments but expects 1 arguments. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.

-[RCTModuleMethod invokeWithBridge:module:arguments:]
    RCTModuleMethod.mm:501
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_queue_serial_drain
_dispatch_queue_invoke
_dispatch_root_queue_drain
_dispatch_worker_thread3
_pthread_wqthread
start_wqthread
```

**Comment by rmevans9** [comment]
I ran into this issue as well. Turns out it is because the location where you should bring in the `xcodeproj` changed so it seems like xcode was using older cached code. Updating the location and rebuilding my app fixed the issue.

What you need to change (NOTE: I had to change this location for both Android and iOS):
iOS: ios/<PROJNAME>.xcodeproj -> Search for LottieReactNative.xcodeproj. There will be a handful of references. Find the one that contains the xcodeprojs location. Update the location to be: "../node_modules/lottie-react-native/src/ios/LottieReactNative.xcodeproj"
Android: android/settings.gradle -> Update the project location for lottie-react-native to be "../node_modules/lottie-react-native/src/android"

**Comment by gpeal** [comment]
@rmevans9 is correct

**Comment by koenpunt** [comment]
Since this is more or less a breaking change, it might be good to mention this in the CHANGELOG.

**Comment by gpeal** [comment]
@koenpunt This is not a breaking change. It's important to keep the native and js versions of libraries in sync. This only happens if they are out of sync.

**Comment by koenpunt** [comment]
> This only happens if they are out of sync.

Not true; the path to the source files are added to the project when `react-native link`ed, so if those paths change, the project doesn't know about the new files. E.g. I had to manually update `android/settings.gradle` and my Xcode project to reference the correct files.

**Comment by Monte9** [comment]
@rmevans9 that works! Thanks for the quick fix.

**Comment by guy-a** [comment]
`react-native unlink lottie-react-native`
and than
`react-native link`

works for me
